# Basic Tensorflow usage

## Load Package

In [1]:
import numpy as np
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
print("Package Load")
print("Current TF version is %s" % (tf.__version__))

Instructions for updating:
non-resource variables are not supported in the long term
Package Load
Current TF version is 2.8.2


In [2]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


## TF Constant

In [3]:
def print_tf(x):
  print("Type is\n %s" % (type(x)))
  print("Value is\n %s" % (x))

hello = tf.constant("Hello, It's me!")
print_tf(hello)

Type is
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is
 Tensor("Const:0", shape=(), dtype=string)


## To make things happen

In [4]:
hello_out = sess.run(hello)
print_tf(hello_out)

Type is
 <class 'bytes'>
Value is
 b"Hello, It's me!"


In [5]:
# OTHER TYPES OF CONSTANT 
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

# AGAIN, RUN 
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

Type is
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is
 Tensor("Const_1:0", shape=(), dtype=float32)
Type is
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is
 Tensor("Const_2:0", shape=(), dtype=float32)
Type is
 <class 'numpy.float32'>
Value is
 1.5
Type is
 <class 'numpy.float32'>
Value is
 2.5


## Operators with fixed inputs

In [6]:
a_sum_b = tf.add(a, b)
print_tf(a_sum_b)

# Run operator
a_sum_b_out = sess.run(a_sum_b)
print_tf(a_sum_b_out)

a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

Type is
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is
 Tensor("Add:0", shape=(), dtype=float32)
Type is
 <class 'numpy.float32'>
Value is
 4.0
Type is
 <class 'numpy.float32'>
Value is
 3.75


## Variables

In [7]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

Type is
 <class 'tensorflow.python.ops.variables.RefVariable'>
Value is
 <tf.Variable 'Variable:0' shape=(5, 2) dtype=float32_ref>


In [8]:
# Get values?
weight_out = sess.run(weight)
print_tf(weight_out)

FailedPreconditionError: ignored

## Why does this error occurs?
variable은 초기화를 해줘야 한다.

In [9]:
# Initialization is required
init = tf.global_variables_initializer()
sess.run(init)
print("Initializing all variables")

Initializing all variables


In [10]:
# Once Initialized
weight_out = sess.run(weight)
print_tf(weight_out)

Type is
 <class 'numpy.ndarray'>
Value is
 [[-0.00098458  0.16154332]
 [ 0.00260623  0.06934891]
 [-0.07952572 -0.09705009]
 [-0.04178767  0.01642416]
 [-0.1539734  -0.02469846]]


## Placeholders

In [11]:
x = tf.placeholder(tf.float32, [None, 5])
print_tf(x)

Type is
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is
 Tensor("Placeholder:0", shape=(?, 5), dtype=float32)


In [12]:
# Operation with placeholders and variables
oper = tf.matmul(x, weight)
print_tf(oper)

Type is
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)


In [13]:
# fedd_dict placeholder
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x : data})
print_tf(oper_out)

Type is
 <class 'numpy.ndarray'>
Value is
 [[-0.11275319 -0.01511847]]


In [14]:
# Batchsize can vary
data = np.random.rand(10, 5)
oper_out = sess.run(oper, feed_dict={x : data})
print_tf(oper_out)

Type is
 <class 'numpy.ndarray'>
Value is
 [[-0.19768308 -0.09314231]
 [-0.10225134  0.04645592]
 [-0.14582632  0.13860852]
 [-0.15812705 -0.01984659]
 [-0.08958057  0.03336663]
 [-0.18244025  0.14813402]
 [-0.13203225  0.04146337]
 [-0.13538013  0.04094876]
 [-0.11098116  0.07583345]
 [-0.17094542  0.07582986]]
